image: node:11.7

cache:
  paths:
    - node_modules/

stages:
  - verify
  - build

test:
  stage: verify
  script:
    - yarn install
    - yarn test:coverage

  # https://gitlab.com/gitlab-org/gitlab-ce/issues/29642
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

lint:
  stage: verify
  script:
    - yarn install
    - yarn lint

electron-win-build:
  stage: build
  image: electronuserland/builder:wine
  script:
    - export REVISION="$(git describe --tags --exact-match 2> /dev/null || git describe --always)"
    - echo $REVISION
    - export REVISION="$(echo 'v1.0.0' || git describe --always)"
    - echo $REVISION
    - yarn install
    - yarn package:win
  artifacts:
    paths:
      - release/*.exe
  only:
    variables:
      - $BUILD_ELECTRON_WINDOWS_APP
