image: node:8

before_script:
  - echo $FIREBASE_API_KEY >> .env

cache:
  paths:
    - node_modules/

stages:
  - build

build:
  stage: build
  image: electronuserland/builder:wine
  script:
    - yarn install
    - yarn package-win
  artifacts:
    paths:
      - release/*.exe
