image: node:8

before_script:
  - yarn install

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - yarn build-renderer
    - yarn test

lint:
  stage: test
  script:
    - yarn lint
