image: node:8

cache:
  paths:
    - node_modules/

stages:
  - build

build:
  stage: build
  image: electronuserland/builder:wine
  script:
    - export REVISION="$(git describe --tags --exact-match 2> /dev/null || git describe --always)"
    - echo $REVISION
    - yarn install
    - yarn package:win
  artifacts:
    paths:
      - release/*.exe
