image: node:11.7

cache:
  paths:
    - node_modules/

stages:
  - verify
  - build

test:
  stage: verify
  script:
    - yarn install
    - yarn test:coverage

  # https://gitlab.com/gitlab-org/gitlab-ce/issues/29642
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

lint:
  stage: verify
  script:
    - yarn install
    - yarn lint

electron-win-build:
  stage: build
  image: electronuserland/builder:wine
  script:
    # Required for `artifactName` in build config
    - export REVISION="$(git describe --always --tags --dirty)"
    - yarn install
    - yarn package:win
  artifacts:
    paths:
      - release/*.exe
  only:
    variables:
      - $BUILD_ELECTRON_WINDOWS_APP
