install:
  - set PATH=C:\Ruby23\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake

artifacts:
  - path: poe-sniper.zip
    name: release archive (x86 binary, config, example input)