# Envirnment:
# - https://www.appveyor.com/docs/build-environment/
# - OpenSSL 1.0.2L (32-bit) (C:\OpenSSL-Win32\bin)
# - Ruby 2.3.3 x86 (C:\Ruby23\bin)

install:
  - set PATH=C:\Ruby23\bin;%PATH%

  # Required because of OCRA issue: https://github.com/larsch/ocra/issues/144
  - git clone https://%gl_user%:%gl_pass%@gitlab.com/5k-mirrors/poe-sniper-pro.git
  - gem build poe-sniper-pro/gem/poe-sniper-pro.gemspec
  - gem install poe-sniper-pro/gem/*.gem --no-document --silent

  - bundle config build.eventmachine --with-ssl-dir=C:\OpenSSL-Win32
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake

artifacts:
  - path: artifacts/poe-sniper-*.zip
    name: release archive (x86 binary, config, example input)