install:
  - set PATH=C:\Ruby23\bin;%PATH%

  - $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - $fileContent += $env:POE_SNIPER_PRO_ACCESS_KEY.Replace(' ', "`n")
  - $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
  - Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent

  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake

artifacts:
  - path: artifacts/poe-sniper-*.zip
    name: release archive (x86 binary, config, example input)