export const ipcEvents = {
  WS_ADD: "wsAdd",
  WS_REMOVE: "wsRemove",
  RESULTS_UPDATE: "resultsUpdate",
  USER_LOGIN: "userLogin",
  USER_LOGOUT: "userLogout",
  SOCKET_STATE_UPDATE: "socketStateUpdate",
  RECONNECT_SOCKET: "reconnectSocket",
  RECONNECT_ALL: "reconnectAllSockets",
  GET_SOCKETS: "getSockets",
  SEND_SOCKETS: "sendSockets",
  TEST_NOTIFICATION: "testNotification",
  SUBSCRIPTION_UPDATE: "subscriptionUpdate",
  GET_PAYING_STATUS: "getPayingStatus",
  SEND_PAYING_STATUS: "sendPayingStatus",
};
